#!/bin/sh

if [ -z $1 ]; then
    FINAL_FOLDER=$CRAFT_PROJECT_DIR/snapbuildtools
else
    FINAL_FOLDER=$CRAFT_PROJECT_DIR/$1
fi

mkdir -p $FINAL_FOLDER
for ITEM in set_python_runtime remove_common parse_env test_doc_checker; do
    cp $CRAFT_PART_SRC/$ITEM/$ITEM.py $FINAL_FOLDER/
done
